# -*- coding: utf-8 -*-
"""Methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xvdR5q7y7-owvjLrpQFPzbYP1IWHEXea

# **Listas (Lists) - Métodos**

## **Métodos disponíveis para listas:**

*   **append**
*   **clear**
*   **copy**
*   **count**
*   **extend**
*   **index**
*   **insert**
*   **pop**
*   **remove**
*   **reverse**
*   **sort**

## **O método 'append' adiciona um único item ao final de uma lista:**
"""

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista.append(10)
print(lista)

"""## **O método 'clear' remove todos os elementos de uma lista:**"""

lista.clear()
print(lista)

"""## **O método 'copy' realiza uma Deep Copy de uma lista:**"""

lista = [1, 2, 3, 4, 5]
copia_lista = lista.copy()

copia_lista.append('Deep Copy!')

print(lista)
print(copia_lista)

"""## **O método 'count' retorna o número de ocorrências de um elemento em uma lista:**"""

lista = [1, 2, 3, 1, 4, 5, 1, 6, 7, 1]
print(lista.count(1))

"""## **O método 'extend' adiciona elementos de outra lista à uma lista:**"""

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista.extend([10, 11, 12, 13, 14, 15])
print(lista)

"""## **O método 'index' retorna o índice de um determinado elemento de uma lista:**"""

print(lista.index(10))  # Retorna o índice do elemento '10'

"""## **O método 'insert' insere um elemento a um determinado índice de uma lista:**"""

lista.insert(0, 0)  # Adiciona o elemento '0' à posição '0'
lista.insert(0, -1)  # Adiciona o elemento '-1' à posição '0'
lista.insert(0, -2)  # Adiciona o elemento '-2' à posição '0'
print(lista)

"""## **O método 'pop' remove o último elemento de uma lista e o retorna:**"""

valor_retirado = lista.pop()
print(valor_retirado)

"""## **O método 'pop' pode também remover um elemento de um índice específico:**"""

valor_retirado = lista.pop(0)
print(valor_retirado)

"""## **O método 'remove' deleta um elemento de uma lista:**"""

lista.remove(5)
print(lista)

"""## **O método 'reverse' inverte a posição de todos os elementos de uma lista:**"""

lista.reverse()
print(lista)

"""## **O método 'sort' organiza os elementos de uma lista:**"""

lista.sort()
print(lista)

"""# **Tuplas (Tuples) - Métodos**

## **Métodos disponíveis para tuplas:**

*  **count**
*  **index**

## **O método 'count' retorna o número de ocorrências de um elemento em uma tupla:**
"""

tupla = 1, 2, 3, 4, 5, 6,
print(tupla.count(3))

"""## **O método 'index' retorna o índice de um determinado elemento de uma tupla:**"""

print(tupla.index(6))

"""# **Dicionários (Dictionaries) - Métodos**

## **Métodos disponíveis para dicionários:**

*   **clear**
*   **copy**
*   **fromkeys**
*   **get**
*   **items**
*   **keys**
*   **pop**
*   **popitem**
*   **setdefault**
*   **update**
*   **values**
"""



"""# **Conjuntos (Sets) - Métodos**

## **Métodos disponíveis para conjuntos:**
"""

